"""empty message

Revision ID: 22edeab3a5ca
Revises: 
Create Date: 2019-01-12 16:10:09.527004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22edeab3a5ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexpic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=62), nullable=True),
    sa.Column('src', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('src')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexpic')
    # ### end Alembic commands ###
